/* Generated by Together */

package com.hp.hpl.sparta.xpath;

/** an expression that returns a boolean value.

   <blockquote><small> Copyright (C) 2002 Hewlett-Packard Company.
   This file is part of Sparta, an XML Parser, DOM, and XPath library.
   This library is free software; you can redistribute it and/or
   modify it under the terms of the <a href="doc-files/LGPL.txt">GNU
   Lesser General Public License</a> as published by the Free Software
   Foundation; either version 2.1 of the License, or (at your option)
   any later version.  This library is distributed in the hope that it
   will be useful, but WITHOUT ANY WARRANTY; without even the implied
   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
   PURPOSE. </small></blockquote>
   @version  $Date: 2005-06-08 13:47:38 +0900 $  $Revision: 3192 $
   @author Eamonn O'Brien-Strain
*/
public abstract class BooleanExpr {
	// 2004.12.27 HAW-Ryan commented throws XPathException	
    public abstract void accept(BooleanExprVisitor visitor)  /*throws XPathException*/;

}

// $Log: BooleanExpr.java,v $
// Revision 1.1  2005/01/24 06:42:52  go
// êVãKìoò^
//
// Revision 1.1  2005/01/24 04:16:28  go
// êVãKìoò^
//
// Revision 1.1  2005/01/11 18:29:34  go
// é¿ã@â“ìÆëŒâû
//
// Revision 1.2  2004/12/27 09:13:34  ryan
// code modification for bytecode reduction
//
// Revision 1.1.1.1  2004/12/16 08:46:46  go
// import to proper
//
// Revision 1.1.1.1  2004/12/02 23:20:43  go
// import to haw cvs
//
// Revision 1.2  2002/12/13 18:08:33  eobrain
// Factor Visitor out into separate visitors for node tests and predicates.
//
// Revision 1.1.1.1  2002/08/19 05:04:05  eobrain
// import from HP Labs internal CVS
//
// Revision 1.3  2002/08/19 00:41:46  eob
// Tweak javadoc comment -- add period (full stop) so that Javadoc knows
// where is end of summary.
//
// Revision 1.2  2002/08/18 23:38:30  eob
// Add copyright and other formatting and commenting in preparation for
// release to SourceForge.
//
// Revision 1.1  2002/02/01 01:17:38  eob
// initial
